services:
  # Robot Client - connects to cloud server and streams video/controls
  robot-client:
    build:
      context: .
      dockerfile: Dockerfile.robot
    container_name: robot-client
    restart: unless-stopped
    privileged: true  # Required for camera and hardware access
    environment:
      - CLOUD_SERVER_URL=${CLOUD_SERVER_URL:-https://teleop.loopcow.com}
      - TURN_USER=${TURN_USER:-}
      - TURN_PASS=${TURN_PASS:-}
      - ROBOT_CAMERA_IDS=${ROBOT_CAMERA_IDS:-0}
      - ROBOT_CAMERA_WIDTH=${ROBOT_CAMERA_WIDTH:-640}
      - ROBOT_CAMERA_HEIGHT=${ROBOT_CAMERA_HEIGHT:-480}
      - ROBOT_CAMERA_FPS=${ROBOT_CAMERA_FPS:-20}
      - ROBOT_DISABLE_AUDIO=${ROBOT_DISABLE_AUDIO:-0}
      - ROBOT_AUDIO_INPUT_DEVICE=${ROBOT_AUDIO_INPUT_DEVICE:-plughw:2,0}
      - ROBOT_AUDIO_INPUT_FORMAT=${ROBOT_AUDIO_INPUT_FORMAT:-alsa}
      - ROBOT_AUDIO_OUTPUT_DEVICE=${ROBOT_AUDIO_OUTPUT_DEVICE:-plughw:2,0}
      - ROBOT_AUDIO_OUTPUT_FORMAT=${ROBOT_AUDIO_OUTPUT_FORMAT:-alsa}
      - ROBOT_VIDEO_BITRATE_KBPS=${ROBOT_VIDEO_BITRATE_KBPS:-1500}
      - ROBOT_ICE_SERVERS=${ROBOT_ICE_SERVERS:-}
      # Use same cache path as host for lerobot calibration
      - HF_HOME=/root/.cache/huggingface
    volumes:
      # Lerobot calibration data (robot configs)
      - ${HOME}/.cache/huggingface/lerobot:/root/.cache/huggingface/lerobot
      # All devices for camera and hardware access
      - /dev:/dev
      # Explicit ALSA devices (helps on some hosts)
      - /dev/snd:/dev/snd
      # For robot control
      - /sys:/sys:ro
    group_add:
      - video      # For camera access
      - dialout    # For serial port access (robot motors)
    network_mode: host  # Required for WebRTC to work properly
